# Generated by Django 6.0.4 on 2026-05-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_user_preferred_room_alter_occupancyhistory_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='x',
            field=models.IntegerField(default=0, help_text='x — позиция по горизонтали (0 = левый край)'),
        ),
        migrations.AddField(
            model_name='place',
            name='y',
            field=models.IntegerField(default=0, help_text='y — позиция по вертикали (0 = верхний ряд)'),
        ),
    ]
