# Generated by Django 6.0.4 on 2026-05-05 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_place_x_place_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='exit_mode',
            field=models.CharField(choices=[('password', 'По паролю'), ('teacher', 'Через преподавателя')], default='password', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='exit_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='rooms.place'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_in_room',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('approved', 'Разрешено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exit_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exit Request',
                'verbose_name_plural': 'Exit Requests',
            },
        ),
    ]
