# Generated by Django 6.0.4 on 2026-05-05 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='place',
            name='x',
        ),
        migrations.RemoveField(
            model_name='place',
            name='y',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_room',
        ),
    ]
