# Generated by Django 6.0.4 on 2026-05-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_place_qr_code_remove_place_x_remove_place_y_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='exit_mode',
        ),
        migrations.RemoveField(
            model_name='room',
            name='exit_password',
        ),
    ]
