# Generated by Django 6.0.4 on 2026-05-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_remove_room_exit_mode_remove_room_exit_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='confirmation_status',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён')], max_length=10, null=True),
        ),
    ]
