# Generated by Django 6.0.4 on 2026-05-06 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_place_confirmation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('scan', 'QR Scan'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('room_created', 'Room Created'), ('room_deleted', 'Room Deleted'), ('place_created', 'Place Created'), ('place_deleted', 'Place Deleted')], max_length=20)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.place')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_log_teacher', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_log_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Log',
                'verbose_name_plural': 'Admin Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
